crate-ci/cargo-release

src/cmd.rs, src/error.rs, src/git.rs, src/main.rs
Use subproject directory name as tag name
=> Subproject tag name

src/cmd.rs, src/git.rs, src/main.rs
A new command line option `--sign` is for this.
=> (feat) added option to sign commits and tags

src/cargo.rs, src/cmd.rs, src/git.rs, src/main.rs
Fixes #6 
Added option to build and upload docs to github pages.
Currently only works for single-crate repository/
=> (feat) option --upload-doc

README.md, src/config.rs, src/main.rs
Adds `dev-version-ext` option to close issue #17.
=> Add dev-version-ext option

src/config.rs, src/error.rs, src/main.rs, src/version.rs
=> More release levels

src/config.rs
This should fix the version upgrade in the _Cargo.toml_ for the released crate.
=> Fix version update in Cargo.lock

src/config.rs
=> fix: Drop Cargo.lock before renaming it

src/main.rs
=> Fix typo in usage

src/config.rs
This undeprecates the source of configuration from cargo manifest
metadata section. It also massages the code-flow to avoid deeply nested
conditionals.
Ref: https://github.com/sunng87/cargo-release/pull/54#issuecomment-413849959
=> config: undeprecated metadata from cargo manifest

Cargo.lock, src/cmd.rs, src/git.rs, src/main.rs
=> Fix default tag prefix to empty

src/config.rs, src/main.rs
Found these as I've worked on switching config handling to serde.
=> Code cleanup

Cargo.lock, Cargo.toml, src/cargo.rs, src/error.rs, src/main.rs, tests/fixtures/mixed_ws/Cargo.lock, tests/fixtures/mixed_ws/Cargo.toml, tests/fixtures/mixed_ws/a/Cargo.toml, tests/fixtures/mixed_ws/a/src/lib.rs, tests/fixtures/mixed_ws/c/Cargo.toml, tests/fixtures/mixed_ws/c/src/lib.rs, tests/fixtures/mixed_ws/src/lib.rs, tests/fixtures/pure_ws/Cargo.lock, tests/fixtures/pure_ws/Cargo.toml, tests/fixtures/pure_ws/a/Cargo.toml, tests/fixtures/pure_ws/a/src/lib.rs, tests/fixtures/pure_ws/b/Cargo.toml, tests/fixtures/pure_ws/b/src/lib.rs, tests/fixtures/pure_ws/c/Cargo.toml, tests/fixtures/pure_ws/c/src/lib.rs
It just so happened that the non-regex parser I used for the lock file also works in workspaces
=> Switch away from regex-based file editors

src/git.rs
=> fix(git): Improve dirty detection

.travis.yml, rustfmt.toml, src/cargo.rs, src/cmd.rs, src/config.rs, src/error.rs, src/git.rs, src/main.rs, src/version.rs
=> rust-fmt and clippy

Cargo.toml, src/cargo.rs, src/cmd.rs, src/config.rs, src/error.rs, src/git.rs, src/main.rs, src/replace.rs, src/version.rs
=> Migrate to 2018 Edition

Cargo.lock, Cargo.toml, src/main.rs
- Accept manifest on the CLI
- Separate workspace vs package logic.
After this
- Accept package selection args via clap-cargo
- Process all selected packages
- Process selected packages in order
=> Prepare for workspace support

docs/reference.md, src/config.rs, src/main.rs
=>  feat(tag): Support customizing the tag name 

src/cargo.rs
=> fix(workspace): Correctly update dev/build dependencies

src/cargo.rs
=> fix(workspace): Only update dependents when needed

.travis.yml, Cargo.lock, Cargo.toml, src/cargo.rs, src/main.rs
- Support cargo's replacement for `--all`, `--workspace`
- Support `-n` for dry-run
And in general, this sees dependencies being updated.
=> Polish CLI arguments

src/cargo.rs
=> fix(output): preserve toml table order

src/main.rs, src/replace.rs
=>  fix(log): Change default level to INFO

src/main.rs
This is to help with changelog management.
Fixes #165
=> feat(replace): Expose tag_name in file replacements

Cargo.lock, Cargo.toml, src/replace.rs
=> feat(replace): Trace diff on dry-run

src/main.rs
Before, crates embedded in crates would flag the root crate as
changed. This now filters out those paths.
This could mislead people if they reach into other crates for files but
the risk seems low for that so I think this is safe enough.
Tested this with liquid which has a root crate and changed leaf crates.
The list of changed files for the root no longer lists other crates'
files in it.
=> fix(change): Improve accuracy of change-detection

README.md, docs/faq.md
This is based  on my experience and some Issues that have been created.
=> Expand documentation

src/main.rs
=> Update change detection log level to debug

src/replace.rs
It is difficult to test out replacements because each replacement gets
its own Diff, you have to mentally piece it all together.
With this change, we batch up the changes so all of them appear in a
single diff.
=> fix(replace): Show a single diff in dry-run

docs/reference.md
Noticed this while reading the reference. Thanks a ton for this amazing tool, and for making it so configurable!
=> fix(reference): correct a small typo

.github/workflows/rust.yml
travis.org is going to shutdown
=> Setup github workflow

CHANGELOG.md, src/cargo.rs
Fixes #271. Tested and works correctly on both the test case in the issue and the original repo that caused the problem.
=> Fix Target Specific Dependencies

src/main.rs
This is a part of #263's sub-module support
=> fix(git): Perform git ops in their relevant dir

Cargo.lock, Cargo.toml
=> fix: --package should be opt-in

src/config.rs
I don't remember seeing this feature before.   Unsure if I missed it or if its new.
=> feat(config): Merge workspace.metadata config

src/git.rs, src/main.rs
=> fix(git): Push when no tracking branch

src/git.rs
The hope is to make it easier to debug problems like #195
=> feat(git): Make it easier to debug dirty

docs/reference.md, src/cargo.rs, src/config.rs, src/main.rs
In case this causes problems, we provide a way out through `--no-verify`
Fixes #215
=> feat(cargo): Run publish w/ dry-run 

docs/faq.md, src/cargo.rs
I think this will take care of #288 but not completely sure.
=> fix(cargo): Handle dependency cycles

src/args.rs, src/cargo.rs, src/config.rs, src/main.rs, src/version.rs
This tries to organize the code to guide the user to where they are wanting to contribute
=> Try to make it easier to get started

src/main.rs
`Cargo.lock` changes do not impact the release of a crate unless its a
`[[bin]]` and someone is going to `cargo install` it.
This is part of #298.
=> fix(cargo): Associate Cargo.lock changes with bins

src/main.rs, src/version.rs
This is prep for #222 though might also help #308
=> refactor: Track bare and full versions

docs/reference.md, src/config.rs, src/main.rs, src/version.rs
=> feat: Opt-in version for consolidated commits

src/cargo.rs
With toml_edit now having a richer API, exploring simpler ways of
writing the depednent version code.
=> refactor: Simplify with toml_edit

src/release.rs
Realized I was overcomplicating this and its easier to implement than I
thought.
Fixes #335
=> fix(publish): Don't fail on dry-run workspace publish

src/release.rs
This should make it easier to patch things up after a failed release.
=> fix(release): Allow 'recovery mode' to skip publishes

src/cargo.rs
When updating a dependent version to a caret version, only include an
explicit caret if the existing version used one. This is implemented on
string types since `semver` doesn't distinguish between an implicit and
explicit caret version.
This is similar in spirit to the implementation in cargo-edit:
https://github.com/killercup/cargo-edit/commit/3de9db7329e847f456ed6cbbbe6ea6b57848f68b
=> feat(cargo): Preserve dependent version format

src/args.rs
=> fix(cli): Have both short and long for metadata

src/git.rs
=> fix(git): Remove ref/file ambiguity

src/args.rs, src/config.rs, src/version.rs
I'm not sure how you feel about these particular clippy lints but the warnings were bugging me.
=> style: Fix clippy warnings

src/cargo.rs, src/release.rs
=> fix(publish): Override default-members

docs/reference.md, src/cmd.rs, src/release.rs
BREAKING CHANGE: Template substitution will now be performed on the hook
argument list
Fixes #469
=> feat(hook)!: Templatize the argument list

docs/reference.md
Should `shared_version` be `shared-version`, or am I misunderstanding what this config is?
=> Potential typo

src/steps/publish.rs, src/steps/push.rs, src/steps/release.rs, src/steps/replace.rs, src/steps/tag.rs, src/steps/version.rs
This will help with automated processes
=> fix!: Error if nothing to publish

docs/reference.md, src/config.rs
=> fix(config)!: Default to always upgrading dependents

src/steps/release.rs
This makes it easier for CI to release just the selected packages.
=> feat: `--unpublished` support for two-phase release

src/ops/git.rs, src/steps/push.rs
Hoping this will help with workflows like in #528
=> fix(git): Auto-detect when a branch isn't worth pushing

docs/reference.md, src/config.rs, src/steps/mod.rs, src/steps/plan.rs
This is mostly as a feature for workspace versions
=> feat(config): Support named groups of shared versions

src/config.rs
=> fix(config): Don't require workspace config outside of workspaces 

Cargo.lock, Cargo.toml, docs/reference.md, src/bin/cargo-release.rs, src/ops/git.rs, src/ops/shell.rs, src/steps/changes.rs, src/steps/mod.rs, src/steps/plan.rs, src/steps/release.rs, src/steps/version.rs
Make it easier to identify what to release and to what version and this makes it easier to write changelogs.
=> feat(changes): New `changes` step

src/ops/replace.rs
=> fix: Log when un-rendered template varabiables are present

src/ops/git.rs
Especially with the new design, versions might already be applied, replacements run, and hooks didn't change anything, so commit will fail with an empty commit error.
We can't quite detect the above state, so rather than trying, I have the commit call automatically skip the commit.  It still does it in dry-run as the tree might still be clean.
Fixes #626
=> fix(commit): Skip if nothing changed

src/config.rs
=> fix(config): Support registry lists for package.publish

Cargo.lock, Cargo.toml
=> fix: Don't lost standard tables nested under dotted tables

Cargo.toml
=> fix: Allow disabling of vendored packages

README.md, docs/faq.md
=> docs(faq): Cover git-cliff usage

src/steps/changes.rs
=> fix(changes): Allow overriding the tag

src/ops/version.rs
Found via rust-lang/cargo#10554
=> fix: Ensure an assert activates

src/ops/cmd.rs
=> fix(hook): Report the command name that failed

docs/reference.md, src/config.rs, src/ops/cargo.rs, src/ops/replace.rs, src/steps/changes.rs, src/steps/commit.rs, src/steps/hook.rs, src/steps/owner.rs, src/steps/publish.rs, src/steps/push.rs, src/steps/release.rs, src/steps/replace.rs, src/steps/tag.rs, src/steps/version.rs
This requires
```console
$ cargo +nightly release -Zworkspace-publish ...
```
=> feat(publish): Use Cargo's workspace publish where possible

Cargo.lock, Cargo.toml, src/steps/plan.rs
=> chore(deps): Update Rust crate cargo_metadata to 0.19

src/steps/release.rs
Fixes https://github.com/crate-ci/cargo-release/issues/908
=> chore(release): add registry name to is_published error
