- README.md
- src/main.rs
Fixes #3 
Added option for release level, you can use `-l` to bump version on `cargo release`. 
* by default, `cargo release` removes prerelease extension (0.1.0-pre -> 0.1.0)
* if `level` is `patch` and current version is a prerelease, it behaves like default; if current version has no extension, it bumps patch version (0.1.0 -> 0.1.1)
* if `level` is `minor`, it bumps minor version (0.1.0-pre -> 0.2.0)
* if `level` is `major`, it bumps major version (0.1.0-pre -> 1.0.0)
> Options for release level

- src/config.rs
- src/main.rs
Rewrite cargo.lock along with cargo.toml. Do not rely on another `cargo update` to sync.
> (feat) auto rewrite cargo.lock

- README.md
- src/config.rs
- src/main.rs
Fixes #21 
Added new option:
`--no-dev-version` will disable version bump after release. 
`no-dev-version` in Cargo.toml is also supported.
> New option: no-dev-version

- Cargo.toml
- README.md
- src/config.rs
- src/error.rs
- src/main.rs
- src/replace.rs
Fixes #23 
This patch allows you to replace custom files on release. For example, you can update README for adding new version number.
> Custom version replacement

- README.md
- src/config.rs
- src/main.rs
This will only override the default tag prefix if `--tag-prefix` is not specified.
This should fix #37.
> Allow specifying the tag prefix in Cargo.toml

- README.md
- src/main.rs
The official manifest has a [key](http://doc.crates.io/manifest.html#the-publish--field-optional) for disable publishing. 
Currently `cargo release` will fail when `cargo publish` is executed and **publish = false**.
With my PR no extra option is added!
> make publish crate optional

- src/config.rs
`cargo release` tries to update the version in the file **Cargo.lock**.
But **Cargo.lock** must not be present! 
From the official [guilde](http://doc.crates.io/guide.html#cargo.toml-vs-cargo.lock):
> If you’re building a library that other projects will depend on, put Cargo.lock in your .gitignore. If you’re building an executable like a command-line tool or an application, check Cargo.lock into git.
Currently if **Cargo.lock** is not present, e.g., after `git clone`, an error appears:
```shell
Update to version 0.14.3 and commit
Fatal: IOError
```
With this PR **Cargo.lock** will be touched only if present!
> Check if Cargo.lock exists before try to adjust version upgrade

- README.md
- src/main.rs
Fixes #52 
The level argument is changed from `cargo release -l <level>` to `cargo release [level]`.
> Level as index argument

- README.md
- src/main.rs
- src/replace.rs
It's replaced by the crate version before `cargo-release` changes it in any way (ie. the version read straight from the `Cargo.toml`).
This can be used, for example, to automatically create links to the diffs between two versions in a changelog.
> Add the `{{prev_version}}` variable

- src/config.rs
- src/main.rs
This introduces a new configuration option "skip-publish", disabled
by default. It is similar to the "publish" parameter in Cargo.toml,
but can be toggled on invidual `cargo release` runs without changing
the manifest.
> config: add a "skip-publish" option

- src/main.rs
This change moves the pre-release hook so that it gets called right
before `git commit` for the release version happens.
This should ensure that if a repo sets a release hook to validate
release readiness, it can validate all the file replacements that
cargo-release has made.
> Reorder pre-release hook

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/replace.rs
Configuration is now defined in one place.
Future directions, left off to keep this change small:
- Change merging of args / config to prevent accidentally reading from a
non-merged value.
- Accept a `--manifest-path` arg and make everything relative to that.
- Support calling `cargo-release` in a child directory.
>  refactor(config): Consolidate logic via serde 

- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/cmd.rs
- src/config.rs
- src/error.rs
- src/main.rs
- tests/fixtures/simple/Cargo.lock
- tests/fixtures/simple/Cargo.toml
- tests/fixtures/simple/src/main.rs
`env!` reads the variable at compile time but this is a variable we
should be reading on the end-user's system, not the system
`cargo-release` was built on.
>  fix(cargo): Read CARGO on user's system 

- src/cargo.rs
This can be useful when testing `cargo-release` without cargo context.
> (fix) fallback to default cargo on PATH

- src/cmd.rs
- src/config.rs
- src/error.rs
- src/git.rs
- src/main.rs
- src/replace.rs
This lays the ground work for either a `--manifest-path` flag or a `--all` flag (workspace support)
> refactor: Centralize cwd assumption

- src/error.rs
- src/git.rs
- src/main.rs
Fixes #67, #92 
Run `git --version` explicitly to ensure git is installed
> Check git availability before workflow

- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/cmd.rs
- src/error.rs
- src/main.rs
For determining the default tag, I did not switch us from finding the git root to finding the workspace root.  I figured that if the crate wasn't in the git root, regardless of the use of workspaces, we probably want to scope the tag.
> Port to cargo_metadata where possible

- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/config.rs
- src/error.rs
- src/main.rs
- src/version.rs
Fixes #77 
This includes switching to CLI arguments using `enum` where possible.  The downside to `arg_enum!` is that `--help` will show the names in uppercase and accepts them case insensitively which is uncommon in CLIs.   We probably want to eventually roll our own set of `impl`s rather than relying on `arg_enum!`
> Update workspace dependents on release

- README.md
This flag is effective but just not documented.
Useful for projects which does `cargo publish` in CI.
Example here: https://github.com/laysakura/fid-rs/blob/v0.1.0/.travis.yml#L57-L62
> Adds doc on `disable-publish` flag

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
> Merge args into config

- Cargo.lock
- src/main.rs
This is effectively calling `cargo-release` for each package.  For
example, it does nothing to consolidate version bump commits before or
after the release.
This uses `clap-cargo` to try to mirror `cargo`s logic for selecting
packages within a workspace.
Fixes #66
> feat(workspace): Release multiple packages at once

- docs/reference.md
I discovered this when trying to configure this in my `Cargo.toml`.
I prefer to have the configuration for this utility in there, instead of `release.toml` and was glad it's an option, but when I was trying to use `metadata.release`. Turns out it's `package.metadata.release`.
I hope this helps others with the same issue I encountered.
PS I don't understand the way the PR was created by GitHub: instead of creating it directly against your repo, it did it by requiring a merge against mine first. Maybe I messed something up. Anyway, if you accept/merge this, please squash it.
>  Doc about configuration in Cargo.toml has a typo 

- src/config.rs
> (feat) add v to default version tag

- src/config.rs
The default value for `pro_release_commit_message` was using `{{version}}` instead of `{{next_version}}`.
> Use {{next_version}} in default for pro_release_commit_message

- src/config.rs
- src/main.rs
Fixes #137 
This patch rename `pro-release-commit-message` to `post-release-commit-message` while maintain backward compatibility for now.
> Rename "pro-release-commit-message" to "post-release-commit-message"

- src/git.rs
- src/main.rs
`git publish` will error on uncommitted changes and untracked files.  We
only had one of these checks, causing us to fail part way through the
release if there was a stale file aorund.
Fixes #145
> fix(git): Error on untracked files

- src/git.rs
- src/main.rs
Ideally, we could give people the option to skip unchanged crates.
We're starting conservativly though in case there are changes that won't
always be detected this way (like updates to dependencies). The big
concern is making this smart enough that people stop thinking while
still being dumb enough that people should still think.
For now, this incorrectly identifies crates as unchanged during dry-run
if we'd update its dependencies as part of releasing a dependency that
lives in the workspace.
For now, this does not respect `package.exclude`, so changes may occur
that should not force the crate to be released.
Fixes #143
BREAKING CHANGE: `{{tag_prefix}}` is now calculated before `{{version}}`
is updated to the current version and should not be trusted.
>  feat(git): Notify user on unchanged crates 

- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/cmd.rs
- src/config.rs
- src/main.rs
- src/shell.rs
This will give the user more conrol over what is outputed.
The default log level is now "error".  Before it was:
- For dry-run: "trace"
- For all else: "debug"
> fix(output): Switch to logging module

- src/cargo.rs
- src/config.rs
- src/main.rs
- src/replace.rs
My goal is to reduce the release logic to eventually allow
- Doing "anything unchanged" checks before the confirmation prompt
- Include dependency updates  in "anything unchanged" when running in
dry-run mode
- A single confirmation prompt
- Potentially consolidate commits
- Consolidate pushes
This stopped short of the refactorings needed to unlock these changes
because it was getting to big.
>  refactor: Pre-compute some information 

- Cargo.lock
- Cargo.toml
- src/main.rs
Instead of processing one crate at a time across all steps, we're going to process one step at a time across all crates.   I have no idea if, in the end, this will make it easier or harder to recover.  The main goal is to work towards:
- Doing "anything unchanged" checks before the confirmation prompt
- Include dependency updates  in "anything unchanged" when running in
dry-run mode, https://github.com/sunng87/cargo-release/issues/150
- A single confirmation prompt, https://github.com/sunng87/cargo-release/issues/138
- Potentially consolidate commits, https://github.com/sunng87/cargo-release/issues/138
- Consolidate pushes, https://github.com/sunng87/cargo-release/issues/138
Besides how things are processed, this does change
- A single push of HEAD is done rather than once per crate (we …
> Batch process each step

- docs/faq.md
- docs/reference.md
- src/config.rs
- src/main.rs
To support workspace-wide configuration, we had to make a small tweak to how the config layering works.  We already needed to do this to help people who want different defaults for their workspace and their root crate.  I thought it already behaved this way and was suggesting people take advantage of it to work around their problems.
I was lazy and also included a documentation update for a past change.
> Allow commits in a workspace to be consolidated.

- docs/faq.md
- docs/reference.md
- src/config.rs
- src/error.rs
- src/main.rs
- src/replace.rs
This has two breaking changes
- For each replacement, an error will occur if no matches for the pattern are found.  This can be reverted with `min = 0`
- Replacements will only happen on major/minor/patch releases. To have a replacement happen on a pre-release, set `prerelease = true`.
Fixes #185 
Fixes #113
> Give users better control over file-replacements

- CHANGELOG.md
- docs/reference.md
- src/cargo.rs
- src/main.rs
Currently, the `cargo publish` step uses whichever token is in the users `~/.cargo/credentials`, or can be overriden by `CARGO_REGISTRY_TOKEN` (for crates.io), but it is sometimes convenient to specify the `--token` parameter for cargo publish, which this PR adds.
> Add `--token` argument

- src/main.rs
The timeout of `wait_for_publish` may be short because it requires disk access.
If the host is under heavy I/O load, `wait_for_publish` takes more than 30s.
> Increase timeout of wait_for_publish

- src/error.rs
- src/main.rs
This addresses #206: When bumping crates to dev versions, update their dependents also. 
Note that due to the way dev versions are likely structured (in prerelease format), in Step 6, we have to do it in the reverse order from Step 2: bump dependents' dependencies _before_ the actual version is bumped; otherwise, cargo is unable to validate the Cargo.toml.
I validated this with the repo linked in https://github.com/sunng87/cargo-release/issues/206#issuecomment-602968271, at branch `cargo-release-test`, with the following commandline: `cargo release --skip-push --skip-publish --skip-tag minor`
Prior to this change, it would error with: 
```
[2020-03-29T18:38:20Z INFO ] Update lib-bar to version 0.2.0
[2020-03-29T18:38:20Z INFO ] Fixing lib-foo's dependency on lib-bar to `^0.2.0` (from …
```
> Update dependents to dev versions

- src/config.rs
- src/main.rs
Fixes #216 
This patch added a new config item `sign_tag` while keeping the original `sign_commit` as it is for backward compatibility.
> Add config item sign_tag 

- src/replace.rs
In the implementation of replace, the logic for determining the maximum number of occurrences should be based on `replace.max`, not `replace.min`.
> Fixes replace bug where min should be max

- src/error.rs
- src/replace.rs
Previously the error message just said file not found as it was just `IOError`.
Added custom logic to check and show the filename in case a file needed for replace is not found.
> Better error message when file to replace not found

- docs/reference.md
- src/config.rs
- src/main.rs
Similarly to `pre-release-replacements` applied prior to committing the release, add `post-release-replacements`.
*Motivation:*
I found myself unable to both have a "clean" release changelog (i.e. no mentioning of "under development") but still have a temporary section in the changelog afterwards in my development branch.
The solution was to add a `post-release-replacement` that behaves just like `pre-release-replacment` with the exception that it is always applied to post-release commit.
> Add config option: post-release-replacements

- Cargo.lock
- Cargo.toml
- src/replace.rs
Using `difference`, we show the entire file, with a character
highlighting adds/reoves and colored output.  For CHANGELOG.md and
lib.rs, these can be quite large, requiring scrolling around to double
check the content.
This switches us to reporting a unified diff, giving the users only what
changed at the cost of
- No coloring.  Could be added in the future
- No context.  The user sees the line number for what changed but thats
it.
From a run of `cargo release` with unified diffs:
```
[2020-11-24T14:01:42Z DEBUG] Substituting values for /Users/edpage/src/personal/assert_cmd/CHANGELOG.md
[2020-11-24T14:01:42Z TRACE] Change:
--- CHANGELOG.md    original
+++ CHANGELOG.md    replaced
@@ -8,0 +9 @@
+## [1.0.3] - 2020-11-24
@@ -220,2 +221,3 @@
-[Unreleased]: …
```
> fix(replace): More compact diff in dry-run

- Cargo.lock
- Cargo.toml
- src/error.rs
Things left out
- semver is coupled to cargo-metadata which is coupled which is cupled
to clap-cargo
- semver-parser completely changed its API, being higher level than
before which makes our job harder to make tweaks to existing version
ranges.
> chore: Upgrade small dep breakages

- src/main.rs
Hey all. Thank you for cargo-release. It's very helpful!
This particular issue (#224) keeps biting me, and while this PR has only a dumb/ugly solution, I do think it should fix the problem. If the chosen time is bad, we could parametrise the second value into argv.
(it's probably possible to write a more advanced solution with a curl to crates.io to check that the previous upload has completed, but I'm not even sure that's perfect if all that's happening under the hood is that the write operation (the publish) propagates to all of crates' replicas.)
> add small thread sleep between publishes - for #224

- src/main.rs
Ref #224
Seems like in #247 a call to `sleep` was missing.
> fix sleep after publish (call sleep) for #224;

- src/cargo.rs
Looks like this was broken in #197 when we made passing arguments to
`cargo publish` more flexible.
Fixes #259
> fix: Correctly pass features to publish

- CHANGELOG.md
- src/main.rs
This adds a command line parameter `--publish-grace-sleep` that defines how long we wait between two invocations of `cargo publish`. The default value is 5.
> Allow to set the time waited between two cargo publishs

- src/main.rs
Fixes #250 
I just simply moved tag push code above the branch push. However, I'm not quite sure if we can optimize the `pushed` check in the new case. And, will the tag push contain all the necessary commits?
> Push tag prior to full push

- CHANGELOG.md
- src/main.rs
No idea how this will interact with #263 but this will help with
implementing #266.
BREAKING CHANGE: When in a workspace, we'll now only look at the
workspace's config for `disable-push` and `push-remote` and no the
package-specific config.
> fix(git)!: Dealing with the remote is workspace-wide

- CHANGELOG.md
- docs/reference.md
- src/config.rs
- src/git.rs
- src/main.rs
This helps when users want to customize CI behavior.
Current limitations include:
* Only on branch and not tag push
* Operates at the workspace level
* No placeholders are supported
Fixes #266
> feat(git): Support push-options

- src/cargo.rs
- src/config.rs
- src/error.rs
- src/main.rs
- src/replace.rs
- src/version.rs
This PR cleans up clippy warnings. Each commit addresses a specific clippy lint in the entire codebase, to facilitate ease of review. The changes themselves should be pretty much non-controversial, but should that not be the case it is easy to revert independently.
Feel free to review and comment.
Addresses  #270
> Make code base clippy-happy

- CHANGELOG.md
- docs/reference.md
- src/config.rs
- src/main.rs
With workspaces, it was annoying to have a push per crate, so I merged
them together.  Then in #267, when implementing push options, I needed
something to read them from, so I made push config exclusively a
workspace-level features.
A better model for this is with `consolidate-commits` where people
opt-in to consolidation, and otherwise we use the crate's config.  This
will also help with #263
Fixes #269
> fix(git): Read push-options for each crate

- src/main.rs
This is a part of #263
Since dirty checks are related to our commiting, I've tied this to
`consolidate-commits`.
> fix(git): Check for dirty packages within each sub-module

- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/error.rs
When I first wrote this, `toml_edit`s API was more limited.  This
modernizes it to how I would write it now.  I assumed this would make it
shorter but apparently not, but I feel this clarifies intent more than
the repeated `contains_key` calls.
In refactoring this, the fix for #274 naturally fell out of it.
Fixes #274
> fix(cargo): Don't panic on unexpected Cargo.tomls

- CHANGELOG.md
- src/main.rs
This introduces an additional check for the 'disable_push' option
at the package level, to allow specific setting for a single entry.
The corresponding workspace option is still evaluated before this.
Closes: https://github.com/sunng87/cargo-release/issues/280
> fix(git): respect 'disable_push' flag at package level

- src/main.rs
- src/version.rs
Besides separating concerns, this is a step towards a potential solution
to #222, see discussion in #246.  Now we are preserving whether the user
used an absolute or relative version.
> refactor(args): Abstract level vs version args

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/error.rs
- src/main.rs
- src/version.rs
Running
`cargo release --dry-run --no-dev-version --skip-publish --workspace --exclude utilities patch`
Treated `patch` as an `exclude` because of a naive use of the `clap`
crate.  This updates to the version of `clap_cargo` with the fix as well
as a whole slew of dependencies.
`clap_cargo`, `cargo_metadata`, `semver`, and `semver_parser` are in
lock-step with each other.  Thankfully, `semver` 1.0 is more like
the old `semver_parser` (before the merge `semver_parser` gained some
`semver` policy) so we could actually upgrade.  This did require
re-implementing some old `semver` logic because it was dropped.
The annoying part was that `cargo_metadata` migrated from `std::path` to `camino`, requiring extra type conversions.
Fixes #284
Fixes #249
Fixes #248
> fix: Don't treat bump as an exclude

- src/main.rs
PR #209 made it so we update dependents on post-release bump, and not
just pre-release.  What was missed is an optimization, saving us from
looking up dependents when there is no version bump, causing us to do no
post-release dependents fix up.
> fix(bump): Ensure post-release dependents fixup works

- src/main.rs
This isn't to the quality to make decisions on behalf of the user, but
its a start.  Remaining work
- Tracking changes-from-lock file
- Telling the user when a change is only because of the lock file
- Looking for changes in depenencies since the curren crates last
release, in case the dependency changed
- Except this will get annoying if the change doesn't matter because
it will keep bugging the user.
This is a step towards #298.
> feat: Notify users of transitive changes

- src/args.rs
- src/main.rs
Enough goes on with a release that I always dry-run before releasing
anyways.  Apparently byron does too since this was baked into
`cargo-smart-release`.  So let's just bake this pattern in.
> feat: Dry-run by default

- src/git.rs
We accidentally double-counted the relative paths, causing us to not
detect changes for crates outside the root directory
> fix(git): Correctly detect non-root changes

- release.toml
- src/main.rs
By turning off consolidate-commits for this project. A better approach
is to provide additional tempalte variables to consolidate-commits
template if current project is not a workspace, or has a fixed release
version.
> fix: next_version not rendered in post commit message

- src/main.rs
We are assuming #224 is now resolved, so removing the sleep.  In case
people run into problems, they can always set the env var to re-enable
it.
Closes #224
> perf: Only post-publish sleep on user request

- Cargo.lock
- Cargo.toml
- src/cargo.rs
Updates crates-index and its usage.
I thought this was related to https://github.com/crate-ci/cargo-release/issues/339 (it is not really).
A dependency bump is probably ok here though. Replaced `.retrieve` with `.update` as retrieve seems to be deprecated.
> Update to crates-index@0.18

- Cargo.toml
I believe this will fix #339.  We've also seen similar problems with not
vendoring with cargo-edit.
Fixes #339
> fix: Vendor libgit2

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/replace.rs
I've twice released the top level crate in a project, forgetting that the changes were in another crate in the workspace.
The hope is to provide messages to users to help them make the right decisions when releasing while not preventing the user from doing what they need to (for example, breaking up a release into multiple calls to release crates at different versions).
This only detects direct changes and not changes from dependencies.
This is another small step towards #298
> feat: Warn when excluded changed packages 

- src/args.rs
- src/main.rs
If a user used an absolute version for one crate but it is a downgrade
for another crate, our reporting missed changes in that excluded crate
will cause the entire operation to fail.
Logging should not cause regular operations to fail.
Fixes #370
> fix: Don't fail due to logging messages 

- src/error.rs
- src/git.rs
- src/release.rs
Just by naming two tags the same, they are shared.  To help catch
problems with this, we added support for detecting a tag
already exists.
Ideally, this is only used with `shared-version = true`.
I wanted to implement this using git2, so I started off porting some other code to git2.  I didn't do too much more out of laziness.
Fixes #333
> feat(git): Allow shared tags 

- docs/reference.md
- src/release.rs
- src/replace.rs
This gives users more control over when metadata shows up in versions
(like updating changelogs, example `Cargo.toml` dependencies, etc).
This also allows specifying only the metadata in places.
BREAKING CHANGE: To get old `{{version}}`, do
`{{version}}+{{metadata}}`.  Note that this impacts the default tags.
Fixes #308
> fix(template)!: Var {{version}} now excludes metadata

- src/version.rs
This only does it when the user didn't specify anything.  Probably should make double-specifying it an error.
> fix(version): Populate metadata field on absolute versions

- src/release.rs
When skipping consolidated commits, we check each released packages
directory for dirty but we commit files in all locations.  We need to
commit all because editing a package can modify the lock file or other
crate's dependencies.  So we change the dirty check to match commit.
Inspired by #336
> fix(git): Match dirty check with our commits

- docs/reference.md
- src/args.rs
- src/cargo.rs
- src/config.rs
- src/release.rs
Add `target` to the config (and `--target` argument) allowing the
verification build to be done against a different target triple. This is
helpful for crates that don't build with the default host target triple.
> feat: Allow specifying build target

- src/args.rs
The default verbosity is 2, which corresponds to info logging. Adding a
single `-v` adds debug logging, and a second one adds trace logging,
which is the most verbose level.
> fix(cli): Fix help text for --verbose

- Cargo.lock
- Cargo.toml
- src/release.rs
Since chrono has been so slow to progress, going ahead and switching to
`time`.  Personally, I find the `time` API annoying.
This has a slight behavior change.  We are now returning the
year/month/day in UTC rather than local time.  That won't usually be
different and most peoples intended audience is the internet and your
local time doesn't matter to them.
> refactor: Move off of chronoe

- src/cargo.rs
Same as #411 (H/T @vmx), but we only ignore dev dependencies; build dependencies are still respected.
Borrowing @vmx's excellent summary:
>This is a fix for the following case. You have a workspace with one root package and another sub-package. That sub-package could e.g. be a derive macro implementation. In order to test that derive macro, you need some functionality from the root packge. Therefore the derive macro has a dev-dependency on the root package.
>
>When publishing such a workspace, currently the way the order is determined, is by looking at the dependencies between the workspace packages. In this case the root depends on the sub-package and the other way round. As the packages are looked at an arbitrary order, it is determined that the root package should be published first …
> fix: ignore dev dependencies in sort_workspace

- src/release.rs
Someone reported confusing behavior in a comment in #298 that turned out
to be because dry-run failed and we had both missed that.  Now, if
dry-run fails, we'll report a clearer message about it.
> fix: Report special dry-run failure message

- src/args.rs
The current `--help` output looks like:
```
--isolated
Ignore implicit configuration files
--sign
Sign both git commit and tag,
--sign-commit
Sign git commit
```
> Fix a typo on the `sign` option

- src/config.rs
Before, we were loading it from the current manifest path.
Fixes #495
> fix(config): Load workspace config from workspace

- src/args.rs
- src/ops/cargo.rs
- src/steps/publish.rs
- src/steps/release.rs
> We may consider deprecating --token in the far future. We are trying
> to move away from passing secrets on the command-line, due to the
> relatively high risk of leaking a secret.
https://github.com/rust-lang/cargo/issues/11136
> fix!: Remove `--token`

- Cargo.lock
- Cargo.toml
- src/ops/git.rs
- src/steps/mod.rs
- src/steps/plan.rs
- src/steps/publish.rs
- src/steps/push.rs
- src/steps/release.rs
- src/steps/replace.rs
- src/steps/tag.rs
- src/steps/version.rs
Previously, `cargo release` was used both for
- Removing pre-release versions
- Recovering from a previous failure
With #530, we now expose the lower level mechanisms to allow people to recover in a more controlled manner and don't need high level recovery support that likely won't work in a users situation because its too abstract.  This opens the door for us to allow users to use the `cargo release version` step to modify versions as they please and release them
BREAKING CHANGE: `cargo release` no longer works as a recovery mode.  Instead, use the individual steps you need to recover
Fixes #482
> fix!: Do full release process for existing crate version

- src/error.rs
- src/steps/mod.rs
- src/steps/publish.rs
- src/steps/push.rs
- src/steps/release.rs
- src/steps/tag.rs
Our exit codes were a bit haphazard.  I think they were meant to represent the stage that failed but we haven't kept up with that (and new stages get added / removed).
I chose the exit code that cargo tends to use.
> fix(cli)!: Use consistent 101 exit code

- docs/reference.md
- src/config.rs
> fix(config)!: Turn off release with `package.publish = false`

- src/steps/mod.rs
- src/steps/publish.rs
- src/steps/release.rs
Not thrilled with erroring but putting in a sleep for 10 minutes would probably make people unhappy.  We can always refine this further.
Fixes #483
> fix(publish): Bail out error for rate limits

- src/steps/version.rs
The user might have changed these already. Let's instead rely on the main `release` warnings.
> fix(version): Don't print meaningless "don't exclude" messages

- src/ops/git.rs
- src/steps/commit.rs
- src/steps/mod.rs
This also caused a rewrite of how we detect dirty trees.  I'm assuming
this resolves #195
Fixes #195
> fix: Show dirty causes by default 

- src/steps/mod.rs
> Crates only count to the rate limit check when being published to crates.io

- src/ops/git.rs
Several times I've run into an issue where:
* My main has diverged from upstream main.
* I use `cargo release` to push both main and a tag.
In this situation, the tag push succeeds while the push to main fails. This isn't desired and in my case breaks automation, which expects the tag to be an ancestor of main.
Use an atomic push to avoid this issue. The man page says:
```
--[no-]atomic
Use an atomic transaction on the remote side if available. Either all
refs are updated, or on error, no refs are updated. If the server does
not support atomic pushes the push will fail.
```
I was a bit worried about the "push will fail" bit, but https://github.blog/2015-04-30-git-2-4-atomic-pushes-push-to-deploy-and-more/ says that atomic pushes were added in 2015. I can't imagine anyone running a 7 year …
> fix: Push git refs atomically

- src/steps/mod.rs
If we are not pushing, we are not behind our push target, so this check should succeed.
Addresses #586.
> steps: don't check push remote when not pushing

- docs/reference.md
- src/config.rs
This reverts commit b35b462dfc4048a6d4a102e14cef66cba0091bf4.
The decision on #399 (implemented in #544) was a mistake.  We still need to allow people to release and now they need to know to force a release=true once we actually implement support for that.  The inconsistent behavior and implementation complexity do not seem worth it.
Fixes #583
> Revert "fix(config)!: Turn off release with `package.publish = false`"

- src/steps/hook.rs
- src/steps/release.rs
- src/steps/replace.rs
https://github.com/crate-ci/cargo-release/commit/11eab502414c3a0040466ac7fa7089e80a836eb1 added support for --unpublished but accidentally always turned it on
> fix: Take the --unpublished option into account

- src/ops/replace.rs
The replacement was not properly logged, making it nearly impossible to figure out in which file a replacement failed, even with trace logging.
To help with that, add a debug message with the full path of the file where replacements are going to be tried in and in case replacement fails, log the file path given in the config.
> fix(cli): properly log replacements

- src/steps/commit.rs
- src/steps/hook.rs
- src/steps/owner.rs
- src/steps/publish.rs
- src/steps/push.rs
- src/steps/release.rs
- src/steps/replace.rs
- src/steps/tag.rs
- src/steps/version.rs
I found I ended up doing this and was confused until I looked at the source code.  This seems a friendly way to guide users into what needs to happen.
> fix: Allow '--dry-run' even though its the default

- docs/reference.md
`post-release-replacements` was removed in [PR #553][], and most of its documentation was removed in [PR #600][]. This removes the last reference to it.
Fixes #630
[PR #553]: https://github.com/crate-ci/cargo-release/pull/553
[PR #600]: https://github.com/crate-ci/cargo-release/pull/600
> docs(ref): Remove reference to removed feature

- docs/reference.md
- src/config.rs
- src/steps/plan.rs
The part I'm most excited about is `metadata = persistent`.  I'm considering adopting metadata to track external state and only specific PRs will update thast external state and I'd rather not set it every time.
Fixes #637
> feat(version): Give more control over metadata handling

- src/ops/cargo.rs
- src/ops/index.rs
- src/steps/hook.rs
- src/steps/mod.rs
- src/steps/publish.rs
- src/steps/release.rs
- src/steps/replace.rs
Ideally we'd find the proper registry and talk to it but that takes a
lot more work to support.
Until then, we'll just act like the registry has no packages in it and
put in some specific hacks to support it.
This should be less brittle than our previous approach which just hoped
we sprinkled `config.registr().is_none()` in the right places.
Fixes #732
> fix(index): Don't talk to crates.io when using alt registry

- src/ops/cargo.rs
Looks like I got the logic backwards and we wait forever for alternative registries.
Fixes #742
> fix: Block for crates.io, not other registries

- src/config.rs
As of Rust 1.75, `Cargo.toml` doesn't have to have a version field.  When its missing, the package version is treated as `0.0.0` and it can't be published.
In support of that, we disallowing packages from being released when they lack a version.  There is nothing to publish and no version to bump, so nothing that can be done. 
For all other cases, we should work just fine because we read the version from `cargo metadata` which will be `0.0.0`.
> feat: Don't release packages without a version

- Cargo.lock
- Cargo.toml
- src/diff.rs
- src/lib.rs
- src/ops/cargo.rs
- src/ops/replace.rs
Gives much better diffs when lines are inserted
Fixes #755
After:
```
Replacing in NEWS.md
--- NEWS.md
+++ NEWS.md
@@ -2,6 +2,8 @@
+## 24.2.1
+
- New: `--features`, `--no-default-features` and `--all-features` options are passed through to Cargo.
- Changed: Minimum Rust version (to build cargo-mutants, not to use it) increased to 1.73.
```
If this is OK in principal I can update all the other call sites that use difflib.
> Use similar rather than difflib to get better diffs

- docs/reference.md
- src/config.rs
- src/steps/mod.rs
- src/steps/publish.rs
- src/steps/release.rs
Closes: #790
With this PR, we should be able to include this in a workspace `Cargo.toml`:
```toml
[workspace.metadata.release]
rate-limit = { existing-packages = 50 }
```
This would allow a maximum of 50 crates to be published together. This is currently hard-coded to be 30.
> feat: support project level `rate_limit`

- Cargo.lock
- Cargo.toml
- docs/reference.md
- src/config.rs
- src/ops/cargo.rs
- src/ops/index.rs
- src/steps/hook.rs
- src/steps/mod.rs
- src/steps/publish.rs
- src/steps/release.rs
- src/steps/replace.rs
This commit adds the ability to select what certificate root store to use when making HTTPS connections. Previously, `cargo-release` was configured to use the default for `tame-index`, which is the "webpki" root of trust maintained by Mozilla. This is a good and reasonable set of certificates, _except_ for users on networks which substitute certificates.
Substituting certificates is something enterprise networks will frequently do so they can man-in-the-middle HTTPS connections made on their network and thus maintain visibility into the network activities of their employees. In this setup, the users' devices will generally be running enterprise-managed software which replaces certificates used by public websites with ones provided by the network software the enterprise uses, with the root …
> Enable selecting system certificate stores.

- src/ops/cargo.rs
- src/steps/publish.rs
- src/steps/release.rs
This has been available in Cargo since 1.66 (2022-12-15) and keeps being a source of problems.
Fixes #813
> fix(publish): Remove our own waiting logic

- src/ops/cmd.rs
There are two reason for this pr:
1. `std::process.Command` recommended us to use canonicalize instead of current_dir [doc](https://doc.rust-lang.org/std/process/struct.Command.html#method.current_dir)
2. Convert to absolute path make us easier to locate problems.
Before:
After:
> feat: Out more error info with cmd run failed

- src/ops/replace.rs
In #604, we held off on this being a warning.
Seems reasonable at this point to give it a try.
Fixes #862
> fix(template): Upgrade unrendered variable to a warning
